#!/bin/bash
GREEN='\e[1;32m'
RED='\e[1;31m'
CYAN='\e[1;36m'
WHITE='\e[0;37m'
PURPLE='\e[95m'
NC='\e[0m'
ERROR='\e[41m'
PASS='\e[102m'

# Prerequisites
printf "\033c"
echo
echo -e "    ${WHITE}|===========================================================|"
echo -e "    ${WHITE}|	Whoa, whoa, whoa, slow down there cowboy. Do you have   |"
echo -e "    ${WHITE}|	this package installed? ${RED}'dos2unix'${WHITE}                      |"
echo -e "    ${WHITE}|	If not, run ${GREEN}'apt-get install dos2unix'${WHITE}			|"
echo -e "    ${WHITE}|===========================================================|"
echo

# Get sudo Priveledge
if [[ $EUID != 0 ]]
then
	echo -e -n "${GREEN}"
	sudo "$0" "$@"
	exit $?
	echo -e -n "${NC}"
fi

# Check For Arguments
version=$1
string1="${CYAN}Insert the name of the file that has issues: ${NC}"
string2="${RED}Making backup file just incase...${NC}"
string3="${RED}Deleting old file that has issues...${NC}"
if  [[ $1 == "-c" ]]
then
	string1="${CYAN}Insert the name of the file that has issues: ${NC}"
	string2="${RED}Making backup file just incase...${NC}"
	string3="${RED}Deleting old file that has issues...${NC}"

elif [[ $1 == "-e" ]]
then
	string1="${CYAN}Insert the name of the file you fucked up: ${NC}"
	string2="${RED}Making backup file incase I fuck shit up...${NC}"
	string3="${RED}Deleting old file that YOU fucked up...${NC}"

elif [[ $1 == "--help" ]]
then
	echo
	echo -e "	${WHITE}Arguments:"
	echo -e "	${PURPLE}-c  --cleantext      Doesnt use any explicit language"
	echo -e "	${PURPLE}-e  --explicittext   Uses what I truley love, anger"
	echo
	exit 1
fi

# Ask For Filename
echo "List of Files:"
echo -e -n "${PURPLE}"
ls -p | grep -v /
echo -e "${WHITE}\____________________/"
echo
echo -e -n $string1
read filevar
echo

# Check If File Was Found
if [[ $filevar == "" ]]
then
	echo  -e "${WHITE}${ERROR}You're supposed to instert a file...${NC}"
	echo
	exit 1
elif [[ -e $filevar ]]
then
	echo -e "${WHITE}${PASS}File Found!${NC}"
	echo
else
	echo -e "${WHITE}${ERROR}File not found! Make sure you entered the correct name!${NC}"
	echo
	exit 1
fi

# Making Backup
printf "\033c"
echo -e $string2
sudo cp $filevar fixfile.backup
echo

# Fix Format
echo -e "${RED}Fixing $filevar's format...${NC}"
sudo dos2unix $filevar
echo

# Copy File
echo -e "${RED}Creating duplicate file...${NC}"
sudo cat $filevar > fixfile.old
echo

# Delete Old File
echo -e $string3
sudo rm $filevar
echo

# Renaming New File
echo -e -n "${CYAN}Insert the name of the new file: ${NC}"
read filenamevar
if [[ $filenamevar == "" ]]
then
	echo
	echo -e -n "${WHITE}Using original file name...${NC}"
	mv fixfile.old $filevar
	echo
	echo
else
	mv fixfile.old $filenamevar
	echo
fi

# Ask To Delete Backup File
echo -e -n "${PURPLE}Delete backup?${WHITE} (y/n): ${NC}"
read answer
case ${answer:0:1} in
	y|Y )
	sudo rm fixfile.backup
	;;
	* )
	echo -e ${PURPLE}Ok, Ok! Chill...${NC}
	mv fixfile.backup ${filenamevar}.backup
	;;
esac
echo

# Finish
echo -e "${WHITE}${PASS}Done :)${NC}"
echo
