#!/bin/bash
# /-----------------------------------\
# 	Blah, blah, blah I wrote
# 	this script, something
#	something, use as you
#       like.
#		-Lacertosus
# \___________________________________/

G='\e[1;32m'
R='\e[1;31m'
C='\e[1;36m'
W='\e[0;37m'
P='\e[95m'
NC='\e[0m'
ERROR='\e[41m'
PASS='\e[102m'

# Prerequisites
printf "\033c"
echo
echo -e "    ${W}|===========================================================|"
echo -e "    ${W}|	Whoa, whoa, whoa, slow down there cowboy. Do you have   |"
echo -e "    ${W}|	this package installed? ${R}'dos2unix'${W}                      |"
echo -e "    ${W}|	If not, run ${G}'apt-get install dos2unix'${W}			|"
echo -e "    ${W}|===========================================================|"
echo

# Get sudo Priveledge
if [[ $EUID != 0 ]]
then
	echo -e -n "${G}"
	sudo "$0" "$@"
	exit $?
	echo -e -n "${NC}"
fi

# Check For Arguments
version=$1
string1="${C}Insert the name of the file that has issues: ${NC}"
string2="${R}Making backup file just incase...${NC}"
string3="${R}Deleting old file that has issues...${NC}"
if  [[ $1 == "-c" ]]
then
	string1="${C}Insert the name of the file that has issues: ${NC}"
	string2="${R}Making backup file just incase...${NC}"
	string3="${R}Deleting old file that has issues...${NC}"

elif [[ $1 == "-e" ]]
then
	string1="${C}Insert the name of the file you fucked up: ${NC}"
	string2="${R}Making backup file incase I fuck shit up...${NC}"
	string3="${R}Deleting old file that YOU fucked up...${NC}"

elif [[ $1 == "--help" ]]
then
	echo
	echo -e "	${W}Arguments:"
	echo -e "	${P}-c  --cleantext      Doesnt use any explicit language"
	echo -e "	${P}-e  --explicittext   Uses what I truley love, anger"
	echo
	exit 1
fi

# Ask For Filename
echo "List of Files:"
echo -e -n "${P}"
ls -p | grep -v /
echo -e "${W}\____________________/"
echo
echo -e -n $string1
read filevar
echo

# Check If File Was Found
if [[ $filevar == "" ]]
then
	echo  -e "${W}${ERROR}You're supposed to instert a file...${NC}"
	echo
	exit 1
elif [[ -e $filevar ]]
then
	echo -e "${W}${PASS}File Found!${NC}"
	echo
else
	echo -e "${W}${ERROR}File not found! Make sure you entered the correct name!${NC}"
	echo
	exit 1
fi

# Making Backup
printf "\033c"
echo -e $string2
sudo cp $filevar fixfile.backup
echo

# Fix Format
echo -e "${R}Fixing $filevar's format...${NC}"
sudo dos2unix $filevar
echo

# Copy File
echo -e "${R}Creating duplicate file...${NC}"
sudo cat $filevar > fixfile.old
echo

# Delete Old File
echo -e $string3
sudo rm $filevar
echo

# Renaming New File
echo -e -n "${C}Insert the name of the new file: ${NC}"
read filenamevar
if [[ $filenamevar == "" ]]
then
	echo
	echo -e -n "${W}Using original file name...${NC}"
	mv fixfile.old $filevar
	echo
	echo
else
	mv fixfile.old $filenamevar
	echo
fi

# Ask To Delete Backup File
echo -e -n "${P}Delete backup?${W} (y/n): ${NC}"
read answer
case ${answer:0:1} in
	y|Y )
	sudo rm fixfile.backup
	;;
	* )
	echo -e ${P}Ok, Ok! Chill...${NC}
	mv fixfile.backup ${filenamevar}.backup
	;;
esac
echo

# Finish
echo -e "${W}${PASS}Done :)${NC}"
echo
