#!/bin/bash
# /-----------------------------------\
# 	Definitly a script custom
# 	to my setup. Edit
#	it to your needs
#		-Lacertosus
# \___________________________________/

G='\e[1;32m' #Green
R='\e[1;31m' #Red
C='\e[1;36m' #Cyan
W='\e[0;37m' #White
P='\e[95m'   #Purple
NC='\e[0m'
FAIL='\e[41m'
PASS='\e[102m'

# Check For .nicrc
if [[ -e ~/.nicrc ]]
then
	echo
else
	echo -e "${W}Whoah, whoah, whoah! Looks like you don't have a ~/.nicrc file, set one up!"
	exit 1
fi

# Get sudo Priveledge
if [[ $EUID != 0 ]]
then
	echo -e -n "${GREEN}"
	sudo "$0" "$@"
	exit $?
	echo -e -n "${NC}"
fi

# Make New Folders
printf "\033c"
echo -e -n "${C}Name of tweak ${P}(normal characters only, no caps)${C}:${W} "
read name

if [[ $name = "" ]]
then
	echo  -e "${W}${FAIL}You're supposed to instert a name...${NC}"
	echo
	exit 1
elif [[ $name =~ [A-Z] ]]
then
	echo
	echo -e "${W}${FAIL}Now, now! No capital letters.${NC}"
	exit
fi

# Make Neccessary Folders/File
echo
echo -e "${R}Making ${W}$name ${R}folder..."
mkdir $name
echo
echo -e "${R}Making ${W}DEBIAN ${R}folder..."
mkdir $name/DEBIAN
echo
echo -e "${R}Making ${W}Library ${R}folder..."
mkdir $name/Library
echo
echo -e "${R}Making ${W}control ${R}file..."
touch $name/DEBIAN/control
echo
echo -e "${R}Adding entry to ${P}packages file..."
echo "dpkg-deb -bZgzip projects/$name LacertosusRepo.github.io/debs" >> ~/Repo/packages
echo
echo -e "${W}${PASS}Done!${NC}"
sleep 3s

# Write control File
printf "\033c"
echo -e "${W}_________________________________"_
echo -e "${P}Enter variables for control file:"
echo
echo -e -n "${C}Display name of tweak:${W} "
read tweakname
echo
echo -e -n "${C}Version:${W} "
read version
echo
echo -e -n "${C}Section:${W} "
read section
echo

source ~/.nicrc
if [[ -e $name/DEBIAN/control ]]
then
	echo "Package: $package_prefix.$name" >> $name/DEBIAN/control
	echo "Name: $tweakname" >> $name/DEBIAN/control
	echo "Depends: mobilesubstrate" >> $name/DEBIAN/control
	echo "Version: $version" >> $name/DEBIAN/control
	echo "Architecture: iphoneos-arm" >> $name/DEBIAN/control
	echo "Description: Very descriptive description" >> $name/DEBIAN/control
	echo "Maintainer: $username" >> $name/DEBIAN/control
	echo "Author: $username" >> $name/DEBIAN/control
	echo "Section: $section" >> $name/DEBIAN/control
	echo "Depiction: http://lacertosusrepo.github.io/depictions/com.lacertosusrepo.$name/index.html" >> $name/DEBIAN/control
	echo "" >> $name/DEBIAN/control
	echo -e "${W}${PASS}Done!${NC}"
	echo
fi
sleep 3s

# Copy .deb To Folder
printf "\033c"
echo -e "${W}List of folders:"
echo -e -n "${P}"
ls -d ~/Projects/*/
echo -e "${W}_______________________________________________"
echo -e -n "${C}Name of tweak project folder:${W} "
read projectfolder

if [[ $projectfolder =~ [A-Z] ]]
then
	echo
	echo -e "${W}${FAIL}Now, now! No capital letters.${NC}"
	rm -r $name
	exit 1
fi

echo
echo -e -n "${C}Version ${P}(i.e. 1-34)${C}:${W} "
read projectversion
sudo find ~/Projects/$projectfolder/packages/ -name "*$projectversion*" -type f -exec cp {} ~/Repo/projects/$name/ \;

# Unpack and deleting .deb
echo
echo -e "${R}Unpacking .deb file..."
for d in $name/*.deb; do dpkg -x $d $name/; done
sudo rm $name/*.deb
echo
echo -e "${W}${PASS}Done!${NC}"
