#!/bin/bash

# remove old debs and packages file
find ~/Dev/Repo/LacertosusRepo.github.io/debs -type f -name '*.deb' -delete
rm ~/Dev/Repo/LacertosusRepo.github.io/Packages.bz2

# move new debs to folder
find ~/Dev/Repo/packages -type f -name '*.deb' -exec cp {} ~/Dev/Repo/LacertosusRepo.github.io/debs/ \;

# create Packages and Packages.bz2 files
dpkg-scanpackages LacertosusRepo.github.io/debs > LacertosusRepo.github.io/Packages
bzip2 -fks ~/Dev/Repo/LacertosusRepo.github.io/Packages

# remove DS_Store files
find . -name '.DS_Store' -type f -delete

# push to github
echo -e -n "Commit Message: "
read commitmessage
cd ~/Dev/Repo/LacertosusRepo.github.io
git add --all
if [ -z "$commitmessage" ]; then
  git commit -m "Repository Update"
else
  git commit -m "$commitmessage"
fi
git push
